r"""
t11f_camera_reliability_stats.py

Analyze real measured tag observations from today's t11 compact console/log data.

Purpose:
    Use real data instead of guessing to answer:
    - How far can front camera see useful tags?
    - How far can rear camera see useful tags?
    - Does rear camera deserve confidence 0.3, 0.5, 0.6, or something else?
    - Should preferred-heading Function B/C use different max distance for front and rear?

Input:
    testLocation\output\t11_console_condensed\tag_measurements.csv

This file is generated by:
    t11c_condense_console_log.py

Outputs:
    testLocation\output\camera_reliability_stats\
        camera_summary.csv
        camera_distance_bins.csv
        recommended_planner_params.csv
        tag_camera_error_stats.csv
        low_quality_observations.csv

Run:
    cd /d D:\Data\_Action\_RunNMS
    python testLocation\t11f_camera_reliability_stats.py
"""

from __future__ import annotations

import csv
import math
import os
import statistics
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Adjustable settings
# ---------------------------------------------------------------------------

# Reliability thresholds for a "useful" measurement.
# These are not final solver thresholds. They are for planning statistics only.
DIST_ERR_GOOD_M = 0.15
ANGLE_ERR_GOOD_DEG = 8.0
YAW_ERR_GOOD_DEG = 25.0

# Candidate distance bins.
DISTANCE_BINS_M = [
    (0.0, 1.0),
    (1.0, 2.0),
    (2.0, 3.0),
    (3.0, 4.0),
    (4.0, 5.0),
    (5.0, 6.0),
    (6.0, 99.0),
]

# Minimum observations needed before trusting a bin.
MIN_BIN_COUNT_FOR_RECOMMENDATION = 3

# Rear confidence recommendation clips.
MIN_REAR_CONFIDENCE = 0.2
MAX_REAR_CONFIDENCE = 1.0


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))
os.chdir(ROOT_DIR)

TEST_DIR = ROOT_DIR / "testLocation"
INPUT_CSV = TEST_DIR / "output" / "t11_console_condensed" / "tag_measurements.csv"
OUT_DIR = TEST_DIR / "output" / "camera_reliability_stats"
OUT_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def safe_float(v: Any, default: Optional[float] = None) -> Optional[float]:
    try:
        if v is None:
            return default
        s = str(v).strip()
        if s == "":
            return default
        return float(s)
    except Exception:
        return default


def safe_int(v: Any, default: Optional[int] = None) -> Optional[int]:
    try:
        if v is None:
            return default
        s = str(v).strip()
        if s == "":
            return default
        return int(float(s))
    except Exception:
        return default


def first_key(row: Dict[str, Any], keys: List[str]) -> Optional[str]:
    for k in keys:
        if k in row:
            return k
    return None


def read_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(
            f"Input not found: {path}\n"
            "Please run t11c_condense_console_log.py first so tag_measurements.csv exists."
        )
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    if not rows:
        with path.open("w", encoding="utf-8", newline="") as f:
            f.write("")
        return
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def mean(vals: List[float]) -> Optional[float]:
    vals = [v for v in vals if v is not None and math.isfinite(v)]
    return statistics.mean(vals) if vals else None


def median(vals: List[float]) -> Optional[float]:
    vals = sorted([v for v in vals if v is not None and math.isfinite(v)])
    return statistics.median(vals) if vals else None


def pctl(vals: List[float], p: float) -> Optional[float]:
    vals = sorted([v for v in vals if v is not None and math.isfinite(v)])
    if not vals:
        return None
    if len(vals) == 1:
        return vals[0]
    idx = (len(vals) - 1) * p / 100.0
    lo = int(math.floor(idx))
    hi = int(math.ceil(idx))
    if lo == hi:
        return vals[lo]
    return vals[lo] * (hi - idx) + vals[hi] * (idx - lo)


def fmt(v: Optional[float], nd: int = 3) -> str:
    if v is None:
        return ""
    return f"{v:.{nd}f}"


def dist_bin_label(d: float) -> str:
    for lo, hi in DISTANCE_BINS_M:
        if lo <= d < hi:
            if hi >= 99:
                return f">={lo:.0f}"
            return f"{lo:.0f}-{hi:.0f}"
    return "unknown"


def normalize_rows(rows: List[Dict[str, str]]) -> List[Dict[str, Any]]:
    out = []
    for r in rows:
        tag_k = first_key(r, ["tag_id", "tag", "Tag"])
        cam_k = first_key(r, ["camera_role", "camera", "cam", "Cam"])
        dist_k = first_key(r, ["meas_distance_m", "distance_m", "Dist"])
        true_dist_k = first_key(r, ["true_distance_m", "TrueD"])
        dist_err_k = first_key(r, ["distance_error_m", "DErr"])

        angle_k = first_key(r, ["meas_angle_deg", "angle_deg", "angle_deg_cw", "Ang"])
        true_angle_k = first_key(r, ["true_angle_deg", "TrueA"])
        angle_err_k = first_key(r, ["angle_error_deg", "AErr"])

        yaw_k = first_key(r, ["meas_yaw_deg", "yaw_deg", "Yaw"])
        true_yaw_k = first_key(r, ["true_yaw_deg", "TrueY"])
        yaw_err_k = first_key(r, ["yaw_error_deg", "YErr"])

        use_k = first_key(r, ["used_in_solution", "used", "Use"])
        x_k = first_key(r, ["x", "x_m", "gt_x_m"])
        y_k = first_key(r, ["y", "y_m", "gt_y_m"])
        h_k = first_key(r, ["heading_deg", "gt_heading_deg", "h_deg"])

        tag_id = safe_int(r.get(tag_k)) if tag_k else None
        cam = str(r.get(cam_k, "")).strip().lower() if cam_k else ""

        dist = safe_float(r.get(dist_k)) if dist_k else None
        true_dist = safe_float(r.get(true_dist_k)) if true_dist_k else None
        dist_err = safe_float(r.get(dist_err_k)) if dist_err_k else None
        if dist_err is None and dist is not None and true_dist is not None:
            dist_err = dist - true_dist

        angle = safe_float(r.get(angle_k)) if angle_k else None
        true_angle = safe_float(r.get(true_angle_k)) if true_angle_k else None
        angle_err = safe_float(r.get(angle_err_k)) if angle_err_k else None
        if angle_err is None and angle is not None and true_angle is not None:
            angle_err = angle - true_angle

        yaw = safe_float(r.get(yaw_k)) if yaw_k else None
        true_yaw = safe_float(r.get(true_yaw_k)) if true_yaw_k else None
        yaw_err = safe_float(r.get(yaw_err_k)) if yaw_err_k else None
        if yaw_err is None and yaw is not None and true_yaw is not None:
            yaw_err = yaw - true_yaw

        used_raw = str(r.get(use_k, "")).strip().lower() if use_k else ""
        used = used_raw in ["y", "yes", "true", "1"]

        if tag_id is None or cam not in ["front", "rear"] or dist is None:
            continue

        abs_dist_err = abs(dist_err) if dist_err is not None else None
        abs_angle_err = abs(angle_err) if angle_err is not None else None
        abs_yaw_err = abs(yaw_err) if yaw_err is not None else None

        good_distance = abs_dist_err is not None and abs_dist_err <= DIST_ERR_GOOD_M
        good_angle = abs_angle_err is not None and abs_angle_err <= ANGLE_ERR_GOOD_DEG
        good_yaw = abs_yaw_err is not None and abs_yaw_err <= YAW_ERR_GOOD_DEG

        # Distance+angle are the core planning quantities.
        useful_da = good_distance and good_angle

        # Yaw is diagnostic, not a hard planner gate.
        useful_day = good_distance and good_angle and good_yaw

        out.append({
            "x": safe_float(r.get(x_k)) if x_k else None,
            "y": safe_float(r.get(y_k)) if y_k else None,
            "heading_deg": safe_float(r.get(h_k)) if h_k else None,
            "tag_id": tag_id,
            "camera_role": cam,
            "distance_m": dist,
            "true_distance_m": true_dist,
            "distance_error_m": dist_err,
            "abs_distance_error_m": abs_dist_err,
            "angle_deg": angle,
            "true_angle_deg": true_angle,
            "angle_error_deg": angle_err,
            "abs_angle_error_deg": abs_angle_err,
            "yaw_deg": yaw,
            "true_yaw_deg": true_yaw,
            "yaw_error_deg": yaw_err,
            "abs_yaw_error_deg": abs_yaw_err,
            "used_in_solution": used,
            "distance_bin_m": dist_bin_label(dist),
            "good_distance": good_distance,
            "good_angle": good_angle,
            "good_yaw": good_yaw,
            "useful_distance_angle": useful_da,
            "useful_distance_angle_yaw": useful_day,
        })

    return out


def summarize_group(rows: List[Dict[str, Any]], group_label: Dict[str, Any]) -> Dict[str, Any]:
    n = len(rows)
    if n == 0:
        return {**group_label, "n": 0}

    dist_err = [r["abs_distance_error_m"] for r in rows if r["abs_distance_error_m"] is not None]
    angle_err = [r["abs_angle_error_deg"] for r in rows if r["abs_angle_error_deg"] is not None]
    yaw_err = [r["abs_yaw_error_deg"] for r in rows if r["abs_yaw_error_deg"] is not None]
    distances = [r["distance_m"] for r in rows if r["distance_m"] is not None]

    useful_da = sum(1 for r in rows if r["useful_distance_angle"])
    useful_day = sum(1 for r in rows if r["useful_distance_angle_yaw"])
    used = sum(1 for r in rows if r["used_in_solution"])

    return {
        **group_label,
        "n": n,
        "used_in_solution_rate": round(used / n, 3),
        "useful_dist_angle_rate": round(useful_da / n, 3),
        "useful_dist_angle_yaw_rate": round(useful_day / n, 3),

        "distance_min_m": fmt(min(distances), 3) if distances else "",
        "distance_max_m": fmt(max(distances), 3) if distances else "",
        "distance_mean_m": fmt(mean(distances), 3),

        "abs_dist_err_mean_m": fmt(mean(dist_err), 3),
        "abs_dist_err_median_m": fmt(median(dist_err), 3),
        "abs_dist_err_p90_m": fmt(pctl(dist_err, 90), 3),

        "abs_angle_err_mean_deg": fmt(mean(angle_err), 2),
        "abs_angle_err_median_deg": fmt(median(angle_err), 2),
        "abs_angle_err_p90_deg": fmt(pctl(angle_err, 90), 2),

        "abs_yaw_err_mean_deg": fmt(mean(yaw_err), 2),
        "abs_yaw_err_median_deg": fmt(median(yaw_err), 2),
        "abs_yaw_err_p90_deg": fmt(pctl(yaw_err, 90), 2),
    }


def recommend_max_distance(bin_rows: List[Dict[str, Any]], camera_role: str) -> float:
    """
    Recommend a planner max distance from measured bins.

    Rule:
        Use the largest bin upper edge whose useful_dist_angle_rate >= 0.6
        and n >= MIN_BIN_COUNT_FOR_RECOMMENDATION.
    """
    best_hi = 4.0
    for r in bin_rows:
        if r.get("camera_role") != camera_role:
            continue
        bin_label = r.get("distance_bin_m", "")
        n = safe_int(r.get("n"), 0) or 0
        rate = safe_float(r.get("useful_dist_angle_rate"), 0.0) or 0.0
        if n < MIN_BIN_COUNT_FOR_RECOMMENDATION:
            continue
        if rate < 0.6:
            continue
        if "-" in bin_label:
            try:
                hi = float(bin_label.split("-")[1])
                best_hi = max(best_hi, hi)
            except Exception:
                pass
    return best_hi


def recommend_rear_confidence(camera_summary: List[Dict[str, Any]]) -> float:
    """
    Estimate rear confidence relative to front from useful distance+angle rates.

    This is intentionally simple and transparent:
        rear_conf = rear_useful_rate / front_useful_rate

    It is clipped to [0.2, 1.0].
    """
    by_cam = {r["camera_role"]: r for r in camera_summary}
    front = by_cam.get("front")
    rear = by_cam.get("rear")
    if not front or not rear:
        return 0.3

    f = safe_float(front.get("useful_dist_angle_rate"), 0.0) or 0.0
    r = safe_float(rear.get("useful_dist_angle_rate"), 0.0) or 0.0
    if f <= 0:
        return 0.3

    conf = r / f
    conf = max(MIN_REAR_CONFIDENCE, min(MAX_REAR_CONFIDENCE, conf))
    return round(conf, 3)


def main() -> None:
    raw_rows = read_rows(INPUT_CSV)
    rows = normalize_rows(raw_rows)

    if not rows:
        raise RuntimeError(
            f"No usable tag rows parsed from {INPUT_CSV}. "
            "Please check column names or send me the header row."
        )

    # Overall camera summary.
    camera_summary = []
    for cam in ["front", "rear"]:
        camera_summary.append(
            summarize_group(
                [r for r in rows if r["camera_role"] == cam],
                {"camera_role": cam},
            )
        )

    # Distance-bin summary by camera.
    bin_summary = []
    for cam in ["front", "rear"]:
        for lo, hi in DISTANCE_BINS_M:
            label = f">={lo:.0f}" if hi >= 99 else f"{lo:.0f}-{hi:.0f}"
            subset = [
                r for r in rows
                if r["camera_role"] == cam and r["distance_bin_m"] == label
            ]
            bin_summary.append(
                summarize_group(
                    subset,
                    {"camera_role": cam, "distance_bin_m": label},
                )
            )

    # Per-tag camera statistics.
    tag_stats = []
    keys = sorted({(r["camera_role"], r["tag_id"]) for r in rows})
    for cam, tid in keys:
        subset = [r for r in rows if r["camera_role"] == cam and r["tag_id"] == tid]
        tag_stats.append(summarize_group(subset, {"camera_role": cam, "tag_id": tid}))

    # Low-quality observations.
    low_quality = []
    for r in rows:
        if not r["useful_distance_angle"]:
            low_quality.append({
                "x": r["x"],
                "y": r["y"],
                "heading_deg": r["heading_deg"],
                "tag_id": r["tag_id"],
                "camera_role": r["camera_role"],
                "distance_m": r["distance_m"],
                "distance_error_m": r["distance_error_m"],
                "angle_error_deg": r["angle_error_deg"],
                "yaw_error_deg": r["yaw_error_deg"],
                "used_in_solution": r["used_in_solution"],
                "distance_bin_m": r["distance_bin_m"],
            })

    front_max = recommend_max_distance(bin_summary, "front")
    rear_max = recommend_max_distance(bin_summary, "rear")
    rear_conf = recommend_rear_confidence(camera_summary)

    recommended = [{
        "front_distance_max_m": front_max,
        "rear_distance_max_m": rear_max,
        "rear_confidence_from_useful_rate": rear_conf,
        "distance_error_good_threshold_m": DIST_ERR_GOOD_M,
        "angle_error_good_threshold_deg": ANGLE_ERR_GOOD_DEG,
        "yaw_error_good_threshold_deg": YAW_ERR_GOOD_DEG,
        "note": "Use front/rear distance limits separately if measured reliability is clearly different.",
    }]

    write_csv(OUT_DIR / "camera_summary.csv", camera_summary)
    write_csv(OUT_DIR / "camera_distance_bins.csv", bin_summary)
    write_csv(OUT_DIR / "recommended_planner_params.csv", recommended)
    write_csv(OUT_DIR / "tag_camera_error_stats.csv", tag_stats)
    write_csv(OUT_DIR / "low_quality_observations.csv", low_quality)

    print("=" * 72)
    print("T11F camera reliability stats")
    print("=" * 72)
    print(f"Input rows parsed : {len(rows)}")
    print(f"Input             : {INPUT_CSV}")
    print(f"Output dir        : {OUT_DIR}")
    print("")

    print("Camera summary:")
    for r in camera_summary:
        print(
            f"{r['camera_role']:<5} n={r['n']:>3} "
            f"useful_DA={r['useful_dist_angle_rate']} "
            f"used_rate={r['used_in_solution_rate']} "
            f"dist_mean={r['distance_mean_m']} "
            f"dist_err_p90={r['abs_dist_err_p90_m']} "
            f"angle_err_p90={r['abs_angle_err_p90_deg']} "
            f"yaw_err_p90={r['abs_yaw_err_p90_deg']}"
        )

    print("")
    print("Distance-bin summary:")
    for r in bin_summary:
        if int(r.get("n", 0)) == 0:
            continue
        print(
            f"{r['camera_role']:<5} bin={r['distance_bin_m']:<4} "
            f"n={r['n']:>3} useful_DA={r['useful_dist_angle_rate']} "
            f"dist_err_p90={r['abs_dist_err_p90_m']} "
            f"angle_err_p90={r['abs_angle_err_p90_deg']}"
        )

    print("")
    print("Recommended planner parameters from this dataset:")
    print(f"front_distance_max_m = {front_max}")
    print(f"rear_distance_max_m  = {rear_max}")
    print(f"rear_confidence      = {rear_conf}")
    print("")
    print("Files written:")
    print(f"  {OUT_DIR / 'camera_summary.csv'}")
    print(f"  {OUT_DIR / 'camera_distance_bins.csv'}")
    print(f"  {OUT_DIR / 'recommended_planner_params.csv'}")
    print(f"  {OUT_DIR / 'tag_camera_error_stats.csv'}")
    print(f"  {OUT_DIR / 'low_quality_observations.csv'}")


if __name__ == "__main__":
    main()
